apiVersion: v1
kind: ConfigMap
metadata:
  name: emptybox-api
data:
  site: https://catbox.moe/
  s3_host: my-store.rook-minio.svc.cluster.local:9000
  s3_bucket: emptybox
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emptybox-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: giovanism/emptybox:flask-dev
        ports:
        - containerPort: 8000
        env:
        - name: MAIN_SITE
          valueFrom:
            configMapKeyRef:
              name: emptybox-api
              key: site
        - name: EMPTYBOX_S3_HOST
          valueFrom:
            configMapKeyRef:
              name: emptybox-api
              key: s3_host
        - name: EMPTYBOX_S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: emptybox-api
              key: s3_bucket
        - name: EMPTYBOX_S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-my-store-access-keys
              key: username
        - name: EMPTYBOX_S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-my-store-access-keys
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: emptybox-api
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: NodePort
