apiVersion: v1
kind: ConfigMap
metadata:
  name: image-processing
data:
  upload_host: emptybox-api.default.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processing
spec:
  selector:
    matchLabels:
      app: image-processing
  template:
    metadata:
      labels:
        app: image-processing
    spec:
      containers:
      - name: api
        image: giovanism/image-processing:latest
        ports:
        - containerPort: 5000
        env:
        - name: IMAGE_PROCESSOR_UPLOAD_HOST
          valueFrom:
            configMapKeyRef:
              name: image-processing
              key: upload_host
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: image-processing
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: image-processing
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: image-processing
spec:
  selector:
    app: image-processing
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
